Add missing Brotli4J libs for aarch64 (#199)
Fixes

```
java.lang.UnsatisfiedLinkError: Failed to find Brotli native library in classpath: /lib/linux-aarch64/libbrotli.so
```

on aarch64 platforms like M-series Macs.

Signed-off-by: Florian Hotze <dev@florianhotze.com>