Fix Ollama chat model usage: Specify HttpClientBuilder to use
Fixes the following exception:

```
java.lang.IllegalStateException: Conflict: multiple HTTP clients have been found in the classpath: [dev.langchain4j.http.client.jdk.JdkHttpClientBuilderFactory, io.quarkiverse.langchain4j.jaxrsclient.JaxRsHttpClientBuilderFactory]. Please explicitly specify the one you wish to use.
llamara-1     |         at dev.langchain4j.http.client.HttpClientBuilderLoader.loadHttpClientBuilder(HttpClientBuilderLoader.java:20)
llamara-1     |         at dev.langchain4j.internal.Utils.getOrDefault(Utils.java:74)
llamara-1     |         at dev.langchain4j.model.ollama.OllamaClient.<init>(OllamaClient.java:50)
llamara-1     |         at dev.langchain4j.model.ollama.OllamaClient$Builder.build(OllamaClient.java:304)
llamara-1     |         at dev.langchain4j.model.ollama.OllamaChatModel.<init>(OllamaChatModel.java:92)
llamara-1     |         at dev.langchain4j.model.ollama.OllamaChatModel$OllamaChatModelBuilder.build(OllamaChatModel.java:334)
```

Signed-off-by: Florian Hotze <dev@florianhotze.com>