Add missing Brotli4J libs for aarch64
Fixes

```
java.lang.UnsatisfiedLinkError: Failed to find Brotli native library in classpath: /lib/linux-aarch64/libbrotli.so
```

Signed-off-by: Florian Hotze <dev@florianhotze.com>